FROM bigeasy/diffuser:base

# With changes in `node_modules`.
#   diff -Naur _node_modules node_modules > node_modules.patch
RUN if [[ -e node_modules.patch ]]; then patch -p 0 < node_modules.patch; fi

COPY ./ ./
