#!/bin/sh

set -e

echo ""

(proof run t/*.t.js | tee .proof.out | proof progress) \
    || (proof errors < .proof.out) \
    || exit 1

if [ "$TRAVIS" = "true" ]; then
  echo ""
  echo "running with coverage"
  t/cover
  istanbul report --format text
fi

echo ""
